# In Travis-CI there is no specific language for Bash, so we use C++ instead.
# Every environment should have Bash and do the trick.
language: cpp
sudo: false
dist: xenial
script:
  - ./continuous-integration/bashlint.sh
  - ./continuous-integration/update-check-no-op.sh
  - ./continuous-integration/update-check-forced-update.sh
  - echo "All tests passed. Have a nice day."
notifications:
  email: false
